name: yt-whisper-2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - selenium
      - requests
      - gradio
      - openai-whisper @ git+https://github.com/openai/whisper.git