name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Set git committer identity
        run: |
          git config --global user.email "danilotpnta@gmail.com"
          git config --global user.name "danilotpnta"
      - name: Pull latest changes from Hugging Face with rebase
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git pull --rebase https://huggingface.co/spaces/danilotpnta/Youtube-Whisper main
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://danilotpnta:$HF_TOKEN@huggingface.co/spaces/danilotpnta/Youtube-Whisper main
